name: Safe Website Scan

on:
  workflow_dispatch:   # allows manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    env:
      TARGET_URL: ${{ secrets.SCAN_TARGET_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p scan-reports

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: ${{ env.TARGET_URL }}
          rules_file_name: '.zap/rules.tsv'  # optional: add if you want to tune rules
          cmd_options: '-r scan-reports/zap-report.html -J scan-reports/zap-report.json'

      - name: List generated reports
        run: ls -la scan-reports

      - name: Upload scan reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports
          path: scan-reports/**
